### ISSUE TITLE
On my site it doesnt work ;(

### ISSUE THREAD

**Issue by Pdzly** [cresterienvogel/gmod-misc#1]
I dont get it why it wont work the QR-Libary.

I tried to make a qr code of an url ( but basic text doesnt work either ) 
its just local and if i make it "manual" in my chrome browser it works everything fine.

my code

if (not timer.Exists("rk_checkqr") and urls[1].data == nil) then
                timer.Create("rk_checkqr", 5, 2, function()
                    urls[1].data = QRCode("TEXT")
                end)
            end
            if (urls[1].data ~= nil) then
                surface.SetMaterial(Material(urls[1].data))
                surface.DrawTexturedRect(w / 2 + 250, 250, 200, 200)
            end

**Comment by Pdzly** [comment]
and TEXT == my url

**Comment by Pdzly** [comment]
Ok normal "TEXT" would work but the link or a little bit longer url like
%22https%3A%2F%2Fsteamcommunity.com%2Fsharedfiles%2Ffiledetails%2F%3Fid%3D2037545211%3F%22
or not encoded
https://steamcommunity.com/sharedfiles/filedetails/?id=2037545211

**Comment by Pdzly** [comment]
But short urls like https://bit.ly/3xsaLyS function i think ? or = makes the problem

**Comment by cresterienvogel** [comment]
![image](https://user-images.githubusercontent.com/35332822/128495060-d95716be-36c3-4aa5-9f7a-3163263b42a0.png)
![image](https://user-images.githubusercontent.com/35332822/128495115-8c28f6dc-e14e-44fa-97a6-b6eb32cd7d6c.png)

**Comment by cresterienvogel** [comment]
![image](https://user-images.githubusercontent.com/35332822/128495174-3691e745-72b7-46ca-bf13-0cefc66b5eb7.png)
a game just can't find a proper file because of that \n, fixing right now tho

**Comment by cresterienvogel** [comment]
should be fixed

**Comment by Pdzly** [comment]
thanks a lot !
